version: '3.8'
services:
  app:
    restart: always
    image: fast_api
    container_name: fast_api
    build: .
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    environment:
      DEBUG: 1
    volumes:
      - ./app:/app.main
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.keys